backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow
# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: hallo # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "date", name: "layout", widget: "hidden", default: "blog"}
      - {label: "title", name: "title", widget: "string"}
      - {label: "draft", name: "date", widget: "datetime"}
      - {label: "type", name: "thumbnail", widget: "image"}
      - label: "fields"
        name: "fields"
        widget: "object"
        fields:
        - { label: 'img1', name: 'img1', widget: 'string', required: false  }
        - { label: 'img2', name: 'img2', widget: 'string', required: false  }
        - { label: 'img3', name: 'img3', widget: 'string', required: false  }
